/**
 * Ripple diagnostic code taxonomy.
 *
 * RPL1xxx - parser, syntax, and module/scope errors
 * RPL11xx - imports, exports, and module boundary errors
 * RPL12xx - identifier, binding, and scope errors
 * RPL13xx - parser recovery and malformed syntax errors
 * RPL2xxx - semantic analysis errors
 * RPL21xx - server block and server/client boundary errors
 * RPL22xx - HTML and template validity errors
 * RPL23xx - styling and class-resolution errors
 * RPL24xx - reactivity and tracking errors
 * RPL25xx - component control-flow errors
 * RPL26xx - component API errors (props, children, refs, dynamic components)
 * RPL27xx - events, bindings, and form semantics
 * RPL28xx - SSR and hydration correctness errors
 * RPL29xx - runtime-constraint compile errors
 * RPL3xxx - warnings
 * RPL9xxx - internal compiler errors and invariants
 */

export const DIAGNOSTIC_CODES = {
	// RPL10xx - parser and scope declaration errors
	DUPLICATE_DECLARATION: 'RPL1001',

	// RPL12xx - identifier, binding, and scope errors
	RESERVED_OBFUSCATED_IDENTIFIER: 'RPL1201',

	// RPL13xx - parser recovery and malformed syntax errors
	RESERVED_ARROW_TYPE_PARAM: 'RPL1301',
	READONLY_NON_ARRAY_TUPLE_TYPE: 'RPL1302',
	TRAILING_COMMA_AFTER_REST_ELEMENT: 'RPL1304',
	AWAIT_KEYWORD_OUTSIDE_ASYNC_OR_MODULE: 'RPL1305',
	FOR_LOOP_VARIABLE_INITIALIZER: 'RPL1307',
	FOR_OF_EXPECTED_INDEX_IDENTIFIER: 'RPL1308',
	FOR_OF_INDEX_ORDER: 'RPL1309',
	RIPPLE_KEYWORD_AS_IDENTIFIER: 'RPL1310',
	HTML_KEYWORD_MISUSE: 'RPL1311',
	REF_KEYWORD_MISUSE: 'RPL1312',
	ATTRIBUTE_VALUE_EXPECTED_EXPRESSION_OR_QUOTED_TEXT: 'RPL1313',
	TRY_MISSING_CATCH_OR_FINALLY: 'RPL1314',
	UNTERMINATED_JSX_CONTENTS: 'RPL1315',
	UNEXPECTED_TEMPLATE_TOKEN_SUGGESTION: 'RPL1316',
	TSX_COMPAT_SELF_CLOSING: 'RPL1317',
	MULTIPLE_STYLE_TAGS: 'RPL1318',
	UNCLOSED_SCRIPT_TAG: 'RPL1319',
	UNCLOSED_STYLE_TAG: 'RPL1320',
	EXPECTED_TSX_COMPAT_CLOSING_TAG: 'RPL1321',
	UNCLOSED_TAG: 'RPL1322',
	UNEXPECTED_CLOSING_TAG: 'RPL1323',
	MISMATCHED_CLOSING_TAG: 'RPL1324',
	CONTINUE_IN_COMPONENT: 'RPL1325',
	BREAK_IN_COMPONENT: 'RPL1326',

	// RPL22xx - HTML and template validity errors
	INVALID_HTML_NESTING: 'RPL2201',

	// RPL21xx - server block and server/client boundary errors
	SERVER_BLOCK_MODULE_ONLY: 'RPL2101',
	SERVER_BLOCK_CLIENT_REFERENCE: 'RPL2102',
	SERVER_IDENTIFIER_MEMBER_ACCESS_ONLY: 'RPL2103',
	SERVER_BLOCK_EXPORTED_COMPONENT_UNSUPPORTED: 'RPL2104',
	SERVER_BLOCK_EXPORTED_MEMBER_EXPRESSION_UNSUPPORTED: 'RPL2105',
	SERVER_BLOCK_EXPORTED_PATTERN_UNSUPPORTED: 'RPL2106',
	SERVER_BLOCK_EXPORTED_DECLARATION_TYPE_UNSUPPORTED: 'RPL2107',
	SERVER_BLOCK_EXPORTED_SPECIFIER_UNSUPPORTED: 'RPL2108',

	// RPL23xx - styling and class-resolution errors
	STYLE_DIRECT_DOM_USAGE: 'RPL2301',
	STYLE_MISSING_STANDALONE_CLASS: 'RPL2302',
	CSS_EXPECTED_TOKEN: 'RPL2303',
	CSS_UNEXPECTED_END_OF_INPUT: 'RPL2304',
	CSS_EMPTY_DECLARATION: 'RPL2305',
	CSS_INVALID_SELECTOR: 'RPL2306',
	CSS_EXPECTED_IDENTIFIER: 'RPL2308',
	STYLE_COMPONENT_ONLY: 'RPL2309',
	STYLE_STATIC_CLASS_ACCESS_ONLY: 'RPL2310',
	STYLE_PROPERTY_ACCESS_ONLY: 'RPL2311',

	// RPL24xx - reactivity and tracking errors
	TRACKED_INTERNAL_PROPERTY_ACCESS: 'RPL2401',
	TRACKED_DIRECT_OBJECT_ACCESS: 'RPL2402',
	TRACK_OUTSIDE_REACTIVE_CONTEXT: 'RPL2403',
	TRACKED_PATTERN_VARIABLE_FORBIDDEN: 'RPL2404',
	AWAIT_IN_CLIENT_CONTROL_FLOW: 'RPL2405',
	IDENTIFIER_DIRECTLY_AFTER_NUMBER: 'RPL2406',

	// RPL25xx - component control-flow errors
	FOR_LOOP_IN_COMPONENT: 'RPL2501',
	SWITCH_CASE_REQUIRES_TEMPLATE: 'RPL2502',
	FOR_OF_REQUIRES_TEMPLATE: 'RPL2503',
	IF_THEN_REQUIRES_TEMPLATE: 'RPL2504',
	IF_ELSE_REQUIRES_TEMPLATE: 'RPL2505',
	TRY_MAIN_REQUIRES_TEMPLATE: 'RPL2506',
	TRY_PENDING_REQUIRES_TEMPLATE: 'RPL2507',
	FOR_IN_LOOP_IN_COMPONENT: 'RPL2508',
	WHILE_LOOP_IN_COMPONENT: 'RPL2509',
	DO_WHILE_LOOP_IN_COMPONENT: 'RPL2510',

	// RPL26xx - component API and declaration-form errors
	VAR_DECLARATION_IN_COMPONENT: 'RPL2601',
	PROPS_MUST_BE_DESTRUCTURED_OBJECT: 'RPL2602',
	RETURN_AT_MODULE_TOP_LEVEL: 'RPL2603',
	RETURN_VALUE_IN_COMPONENT: 'RPL2604',
	ELEMENT_AS_GENERIC_EXPRESSION: 'RPL2605',
	ELEMENT_OUTSIDE_COMPONENT: 'RPL2606',
	HEAD_CANNOT_HAVE_ATTRIBUTES: 'RPL2607',
	HEAD_MUST_HAVE_CHILDREN: 'RPL2608',
	TITLE_TEXT_ONLY: 'RPL2609',
	INVALID_HEAD_ELEMENT: 'RPL2610',
	SCRIPT_OUTSIDE_HEAD: 'RPL2611',
	EMPTY_ATTRIBUTE_EXPRESSION: 'RPL2612',
	DOM_KEY_ATTRIBUTE_FORBIDDEN: 'RPL2613',
	VOID_ELEMENT_CHILDREN_FORBIDDEN: 'RPL2614',
	IMPLICIT_AND_EXPLICIT_CHILDREN_CONFLICT: 'RPL2615',
	CHILDREN_PROP_ON_ELEMENT_FORBIDDEN: 'RPL2616',
	CHILDREN_INTERPOLATION_FORBIDDEN: 'RPL2617',

	// RPL29xx - runtime-constraint compile errors
	RIPPLE_NAMESPACE_READ_ONLY: 'RPL2901',
	RIPPLE_NAMESPACE_CALL_REQUIRED: 'RPL2902',
	RIPPLE_NAMESPACE_COMPUTED_ACCESS_FORBIDDEN: 'RPL2903',
	RIPPLE_ARRAY_NAMESPACE_MEMBER_RESTRICTED: 'RPL2904',
	RIPPLE_NAMESPACE_MEMBER_ACCESS_FORBIDDEN: 'RPL2905',
	RIPPLE_NAMESPACE_MEMBER_CALL_REQUIRED: 'RPL2906',
	RIPPLE_NAMESPACE_NEW_FORBIDDEN: 'RPL2907',
};
