/** @import { ResolvedConfig } from 'vite' */

import fs from 'node:fs';
import path from 'node:path';

export const RESOLVED_ADAPTER_BROWSER_STUB_ID = '\0ripple:adapter-browser-stub';
export const SERVER_ONLY_ADAPTER_IDS = new Set([
	'@ripple-ts/adapter-node',
	'@ripple-ts/adapter-bun',
	'@ripple-ts/adapter-vercel',
]);

/** @type {Map<string, string>} */
const generated_file_cache = new Map();

/**
 * @returns {string}
 */
export function create_adapter_browser_stub_source() {
	return `export const runtime = undefined;
export function serve() {
  throw new Error('[ripple] Server adapters cannot run in the browser.');
}
export function nodeRequestToWebRequest() {
  throw new Error('[ripple] Node request helpers cannot run in the browser.');
}
export function webResponseToNodeResponse() {
  throw new Error('[ripple] Node response helpers cannot run in the browser.');
}
`;
}

/**
 * @param {ResolvedConfig} viteConfig
 * @returns {string}
 */
export function get_project_generated_dir(viteConfig) {
	return path.join(viteConfig.cacheDir, 'project');
}

/**
 * @param {ResolvedConfig} viteConfig
 * @param {string} name
 * @param {string} source
 * @returns {string}
 */
export function write_project_generated_file(viteConfig, name, source) {
	const dir = get_project_generated_dir(viteConfig);
	const file = path.join(dir, name);

	if (generated_file_cache.get(file) === source && fs.existsSync(file)) {
		return file;
	}

	fs.mkdirSync(dir, { recursive: true });
	if (!fs.existsSync(file) || fs.readFileSync(file, 'utf-8') !== source) {
		fs.writeFileSync(file, source);
	}
	generated_file_cache.set(file, source);
	return file;
}

/**
 * @param {{ configPath: string, staticEntries: string[] }} options
 * @returns {string}
 */
export function create_client_entry_source(options) {
	const static_imports = options.staticEntries
		.map((entry) => `  ${JSON.stringify(entry)}: () => import(${JSON.stringify(entry)}),`)
		.join('\n');

	return `// Auto-generated by @ripple-ts/vite-plugin.
// This file is written to Vite's cacheDir/project folder.

import { hydrate, mount } from 'ripple';
import rippleConfig from ${JSON.stringify(options.configPath)};

const routeModules = {
${static_imports}
};

const renderRoutes = (rippleConfig.router?.routes ?? []).filter((route) => route.type === 'render');
const rootBoundary = rippleConfig.rootBoundary;

function getRouteEntryPath(entry) {
  return Array.isArray(entry) ? entry[1] : entry;
}

function getRouteEntryExportName(entry) {
  return Array.isArray(entry) ? entry[0] : undefined;
}

function getComponentExport(module, exportName) {
  if (exportName && typeof module[exportName] === 'function') return module[exportName];
  if (typeof module.default === 'function') return module.default;
  return Object.entries(module).find(([key, value]) => typeof value === 'function' && /^[A-Z]/.test(key))?.[1];
}

async function resolveRouteComponent(data) {
  const route =
    typeof data.routeIndex === 'number' ? renderRoutes[data.routeIndex] : undefined;

  const entry = route?.entry ?? data.entry;
  const entryPath = getRouteEntryPath(entry);
  const exportName = getRouteEntryExportName(entry);
  if (!entryPath) return null;

  const loadModule = routeModules[entryPath] ?? (() => import(/* @vite-ignore */ entryPath));
  const Component = getComponentExport(await loadModule(), exportName);
  if (!Component) return null;

  // Load the route layout so hydration sees the same component tree as the
  // server render and the layout's CSS is part of the client graph.
  const layoutPath = typeof route?.layout === 'string' ? route.layout : undefined;
  if (layoutPath) {
    const loadLayout = routeModules[layoutPath] ?? (() => import(/* @vite-ignore */ layoutPath));
    const Layout = getComponentExport(await loadLayout());
    if (Layout) return { Component, Layout };
  }

  return { Component };
}

(async () => {
  try {
    const data = JSON.parse(document.getElementById('__ripple_data').textContent);
    const target = document.getElementById('root');
    const resolved = await resolveRouteComponent(data);

    if (!resolved || !target) {
      console.error('[ripple] Unable to hydrate route: missing component export or #root target.');
      return;
    }

    // With a layout, hydrate the layout and pass the page as its children
    // prop — the same tree the server rendered.
    const { Component, Layout } = resolved;
    const pageProps = { params: data.params };
    const root = Layout ?? Component;
    const props = Layout ? { ...pageProps, children: () => Component(pageProps) } : pageProps;

    try {
      hydrate(root, { target, props, rootBoundary });
    } catch (error) {
      console.warn('[ripple] Hydration failed, falling back to mount.', error);
      mount(root, { target, props, rootBoundary });
    }
  } catch (error) {
    console.error('[ripple] Failed to bootstrap client hydration.', error);
  }
})();
`;
}

/**
 * @param {string} filename
 * @param {string} root
 * @returns {string}
 */
export function to_vite_root_import(filename, root) {
	return '/' + path.relative(root, filename).split(path.sep).join('/');
}
